qt 5.9

diff --git a/texmaker/patches/01-texmaker.patch b/texmaker/patches/01-texmaker.patch
--- a/texmaker/patches/01-texmaker.patch
+++ b/texmaker/patches/01-texmaker.patch
@@ -1,46 +1,50 @@
-diff -Naurd a/BUILD.sh b/BUILD.sh
---- a/BUILD.sh	2013-03-05 11:52:44.000000000 +0100
-+++ b/BUILD.sh	2013-03-10 18:59:36.000000000 +0100
-@@ -2,9 +2,9 @@
- echo "Texmaker compilation :"
- echo "----------------------------------------"
- echo "Enter path to QT:"
--read QTDIR
-+QTDIR=/usr/lib/qt5
- echo "Enter SYSTEM (1: UNIX ; 2: MACOSX) :"
--read SYSTEM
-+SYSTEM=1
- PATH=$QTDIR/bin:$PATH
- LD_LIBRARY_PATH=$QTDIR/lib:$LD_LIBRARY_PATH
- DYLD_LIBRARY_PATH=$QTDIR/lib:$DYLD_LIBRARY_PATH
-@@ -12,11 +12,11 @@
- if [ "$SYSTEM" = 1 ] 
- then
- echo "Enter PREFIX (/usr , /usr/local or /opt) :"
--read PREFIX
-+PREFIX=/usr
- echo "Enter  DIRECTORY for the desktop file (/usr/share/applications) :"
--read DESKTOPDIR
-+DESKTOPDIR=/usr/share/applications
- echo "Enter  DIRECTORY for the icon file (/usr/share/pixmaps) :"
--read ICONDIR
-+ICONDIR=/usr/share/pixmaps
- $QTDIR/bin/qmake PREFIX=$PREFIX DESKTOPDIR=$DESKTOPDIR ICONDIR=$ICONDIR texmaker.pro
- make
- make install
-diff -Naurd a/utilities/texmaker.desktop b/utilities/texmaker.desktop
---- a/utilities/texmaker.desktop	2012-05-20 15:08:54.000000000 +0200
-+++ b/utilities/texmaker.desktop	2014-05-05 20:19:41.000000000 +0200
-@@ -1,10 +1,11 @@
+diff -Naur orig/BUILD.sh patched/BUILD.sh
+--- orig/BUILD.sh	2017-07-10 10:22:17.134739579 +0200
++++ patched/BUILD.sh	2017-07-15 22:45:54.291345045 +0200
+@@ -24,8 +24,8 @@
+ 	echo "Texmaker compilation:"
+ 	echo "----------------------------------------"
+ 	while [[ -z ${QTDIR} ]]; do # loop until input is provided
+-		read -p "Enter full path to QT (qmake): " QTDIR # get path to qmake
+-			if [[ ! -f ${QTDIR}/qmake ]]; then # check if gmake is present in the provided path
++		QTDIR=/usr/lib/qt5
++			if [[ ! -f ${QTDIR}/bin/qmake ]]; then # check if gmake is present in the provided path
+ 				echo -ne "${txtred}Error${txtrst}: Unable to find qmake in \"${QTDIR}\"\n"
+ 				QTDIR=""
+ 			fi
+@@ -44,7 +44,7 @@
+ 	else
+ 		echo -ne "\rUnable to detect system automatically!\n"
+ 		while [[ -z ${SYSTEM} ]]; do
+-			read -p "Enter System type (1: UNIX ; 2: MACOSX): " SYSTEM
++			SYSTEM="1"
+ 		done
+ 	fi
+ 	echo -ne "\n" # just print a space to make a nicer output
+@@ -55,13 +55,13 @@
+ 
+ 	if [[ ${SYSTEM} == "1" ]]; then # run if linux is detected
+ 		while [[ -z ${PREFIX} ]]; do # get installation path for Texmaker
+-			read -p "Enter installation path (example: /usr , /usr/local or /opt): " PREFIX
++			PREFIX=/usr
+ 		done
+ 		while [[ -z ${DESKTOPDIR} ]]; do # get installation path for .desktop file
+-			read -p "Enter directory for the desktop file (example: /usr/share/applications): " DESKTOPDIR
++			DESKTOPDIR=/usr/share/applications
+ 		done
+ 		while [[ -z ${ICONDIR} ]]; do # get installation path for Desktop-icon
+-			read -p "Enter directory for the icon file (example: /usr/share/pixmaps): " ICONDIR
++			ICONDIR=/usr/share/pixmaps
+ 		done
+ 		${QTDIR}/qmake PREFIX=${PREFIX} DESKTOPDIR=${DESKTOPDIR} ICONDIR=${ICONDIR} texmaker.pro # run qmake
+ 		QMAKE_EXIT="$?" # get exit code of qmake
+diff -Naur orig/utilities/texmaker.desktop patched/utilities/texmaker.desktop
+--- orig/utilities/texmaker.desktop	2017-07-14 01:16:02.134739579 +0200
++++ patched/utilities/texmaker.desktop	2017-07-15 22:40:06.454884889 +0200
+@@ -1,5 +1,5 @@
  [Desktop Entry]
 -Categories=Office;Publishing;Qt;X-SuSE-Core-Office;X-Mandriva-Office-Publishing;X-Misc;
 +Categories=Office;Publishing;Qt;X-Misc;
  Exec=texmaker %F
  GenericName=LaTeX Editor
  GenericName[fr]=Editeur LaTeX
- Comment=LaTeX development environment
- Comment[fr]=Environnement de développement LaTeX
-+Comment[hu]=LaTeX szerkesztő
- Icon=texmaker
- MimeType=text/x-tex;
- Name=Texmaker
